### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by Strum355** [UCCNetsoc/fail2rest#1]
At this uses the fail2ban socket, this should be easily dockerizable.

Inspirations: https://hub.docker.com/r/whiledo/docker-remote-api-tls/
This uses the docker socket to allow remote API usage, authentication happens with shared certs

**Comment by Avitus27** [comment]
Looks like whiledo's container is deprecated. Recommended to use https://hub.docker.com/r/kekru/docker-remote-api-tls

**Comment by Strum355** [comment]
This was just as a source of inspiration as to how it could be done with tls certs for auth. We use portainer agents instead of docker-remote-api-tls
