### ISSUE TITLE
How to settup config ?

### ISSUE THREAD

**Issue by Fluoo** [UCCNetsoc/fail2rest#8]
Hello,

I used fail2rest from sean-Der on my old server. Now I build a new server and I have problem installing fail2rest from sean-der.
It seems the project is abandonned so I tried to install your version.

When I launch fail2rest I have error about netsoc-consul. I try to disable it but it seems that I haven't the good option to set up the config.
I have try to launch with :
fail2rest -config=/etc/fail2rest.json
or
fail2rest -config /etc/fail2rest.json
but it seems I have the default config in the output : 
2021-06-30 10:19:10+02:00 [DEBUG] config.go:22:PrintSettings() config:
{
        "consul": {
                "enabled": true,
                "fail2rest": "fail2rest-token",
                "host": "netsoc-consul:8500",
                "token": ""
        },
        "fail2ban": {
                "socket": "/var/run/fail2ban/fail2ban.sock"
        },
        "fail2rest": {
                "auth_enabled": true,
                "production": false,
                "secret": "[secret]"
        },
        "http": {
                "port": 8080
        }
}
2021-06-30 10:19:10+02:00 [INFO ] main.go:36:main() Initialising fail2ban connection
        fail2ban socket='/var/run/fail2ban/fail2ban.sock'
2021-06-30 10:19:10+02:00 [INFO ] main.go:43:main() Initialising HTTP Server
        port='8080'
2021-06-30 10:19:11+02:00 [ERROR] consul.go:107:getSharedSecret() failed to get shared secret
        count='4' error='Get "http://netsoc-consul:8500/v1/kv/fail2rest-token": dial tcp: lookup netsoc-consul on 213.186.33.99:53: no such host' limit='4'

cat /etc/fail2rest.json
{
        "consul": {
                "enabled": false,
                "fail2rest": "fail2rest-token",
                "host": "netsoc-consul:8500",
                "token": ""
        },
        "fail2ban": {
                "socket": "/var/run/fail2ban/fail2ban.sock"
        },
        "fail2rest": {
                "auth_enabled": false,
                "production": true,
                "secret": "[secret]"
        },
        "http": {
                "port": 5010
        }
}

**Comment by ericm** [comment]
Could you try setting the environment variable `export CONSUL_ENABLED=false` and then run it again?

**Comment by Fluoo** [comment]
Hello,
Thanks for your answer.

I have try to make export CONSUL_ENABLED=false and it solved a part of my problem.
When I launch fail2rest in the console, I haven't the error and fail2rest listen on port 8080.
But I make a request I have a "HTTP/1.1 403 Forbidden". I think it's due to the "auth_enabled" option.

With your version of fail2rest it's not possible to use a configuration file like /etc/fail2rest.json ? 
How can I disabled the auth_enabled ? i only use fail2rest on localhost.
I use a service file to launch fail2rest but in this case it doesn't work, I still have a problem with consul. I have try to add "CONSUL_ENABLED=false" in my /etc/environement but it didn't do anything.

cat /etc/systemd/system/fail2rest.service
[Unit]
Description=fail2ban REST server
Documentation=man:fail2rest(1)
ConditionPathExists=/etc/fail2rest.json
After=fail2ban.service

[Service]
ExecStart=/usr/bin/fail2rest -config=/etc/fail2rest.json

[Install]
WantedBy=multi-user.target

Regards

**Comment by ericm** [comment]
Could you set the consul variable and `FAIL2REST_AUTH_ENABLED=false` using the [environment directive in the service file](https://kinvolk.io/docs/flatcar-container-linux/latest/setup/systemd/environment-variables/)

**Comment by Fluoo** [comment]
Hello,

It works !
A big thanks for the tutoriel to set up environement variable in service file, I looking for that but don't find it.

I have found how to change port of fail2rest.
Thanks again.
